// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: basic/v1/basic.proto

package basicV1

import (
	v1 "github.com/soundphilosopher/basic-grpc-service-go/sdk/basic/service/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_basic_v1_basic_proto protoreflect.FileDescriptor

const file_basic_v1_basic_proto_rawDesc = "" +
	"\n" +
	"\x14basic/v1/basic.proto\x12\bbasic.v1\x1a\x1ebasic/service/v1/service.proto2\x84\x02\n" +
	"\fBasicService\x12J\n" +
	"\x05Hello\x12\x1e.basic.service.v1.HelloRequest\x1a\x1f.basic.service.v1.HelloResponse\"\x00\x12K\n" +
	"\x04Talk\x12\x1d.basic.service.v1.TalkRequest\x1a\x1e.basic.service.v1.TalkResponse\"\x00(\x010\x01\x12[\n" +
	"\n" +
	"Background\x12#.basic.service.v1.BackgroundRequest\x1a$.basic.service.v1.BackgroundResponse\"\x000\x01BHZFgithub.com/soundphilosopher/basic-grpc-service-go/sdk/basic/v1;basicV1b\x06proto3"

var file_basic_v1_basic_proto_goTypes = []any{
	(*v1.HelloRequest)(nil),       // 0: basic.service.v1.HelloRequest
	(*v1.TalkRequest)(nil),        // 1: basic.service.v1.TalkRequest
	(*v1.BackgroundRequest)(nil),  // 2: basic.service.v1.BackgroundRequest
	(*v1.HelloResponse)(nil),      // 3: basic.service.v1.HelloResponse
	(*v1.TalkResponse)(nil),       // 4: basic.service.v1.TalkResponse
	(*v1.BackgroundResponse)(nil), // 5: basic.service.v1.BackgroundResponse
}
var file_basic_v1_basic_proto_depIdxs = []int32{
	0, // 0: basic.v1.BasicService.Hello:input_type -> basic.service.v1.HelloRequest
	1, // 1: basic.v1.BasicService.Talk:input_type -> basic.service.v1.TalkRequest
	2, // 2: basic.v1.BasicService.Background:input_type -> basic.service.v1.BackgroundRequest
	3, // 3: basic.v1.BasicService.Hello:output_type -> basic.service.v1.HelloResponse
	4, // 4: basic.v1.BasicService.Talk:output_type -> basic.service.v1.TalkResponse
	5, // 5: basic.v1.BasicService.Background:output_type -> basic.service.v1.BackgroundResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_basic_v1_basic_proto_init() }
func file_basic_v1_basic_proto_init() {
	if File_basic_v1_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_v1_basic_proto_rawDesc), len(file_basic_v1_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_basic_v1_basic_proto_goTypes,
		DependencyIndexes: file_basic_v1_basic_proto_depIdxs,
	}.Build()
	File_basic_v1_basic_proto = out.File
	file_basic_v1_basic_proto_goTypes = nil
	file_basic_v1_basic_proto_depIdxs = nil
}
