// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: basic/service/v1/service.proto

package basicServiceV1

import (
	v1 "github.com/soundphilosopher/basic-grpc-service-go/sdk/io/cloudevents/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_PROCESS_STATE_UNSPECIFIED         State = 0
	State_PROCESS_STATE_PROCESS             State = 1
	State_PROCESS_STATE_COMPLETE            State = 2
	State_PROCESS_STATE_ERROR               State = 3
	State_PROCESS_STATE_COMPLETE_WITH_ERROR State = 4
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_PROCESS",
		2: "PROCESS_STATE_COMPLETE",
		3: "PROCESS_STATE_ERROR",
		4: "PROCESS_STATE_COMPLETE_WITH_ERROR",
	}
	State_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED":         0,
		"PROCESS_STATE_PROCESS":             1,
		"PROCESS_STATE_COMPLETE":            2,
		"PROCESS_STATE_ERROR":               3,
		"PROCESS_STATE_COMPLETE_WITH_ERROR": 4,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_basic_service_v1_service_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_basic_service_v1_service_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{0}
}

type SomeServiceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeServiceData) Reset() {
	*x = SomeServiceData{}
	mi := &file_basic_service_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeServiceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeServiceData) ProtoMessage() {}

func (x *SomeServiceData) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeServiceData.ProtoReflect.Descriptor instead.
func (*SomeServiceData) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SomeServiceData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SomeServiceData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SomeServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Data          *SomeServiceData       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeServiceResponse) Reset() {
	*x = SomeServiceResponse{}
	mi := &file_basic_service_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeServiceResponse) ProtoMessage() {}

func (x *SomeServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeServiceResponse.ProtoReflect.Descriptor instead.
func (*SomeServiceResponse) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *SomeServiceResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SomeServiceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SomeServiceResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SomeServiceResponse) GetData() *SomeServiceData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SomeServiceResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*SomeServiceResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeServiceResponses) Reset() {
	*x = SomeServiceResponses{}
	mi := &file_basic_service_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeServiceResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeServiceResponses) ProtoMessage() {}

func (x *SomeServiceResponses) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeServiceResponses.ProtoReflect.Descriptor instead.
func (*SomeServiceResponses) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *SomeServiceResponses) GetResponses() []*SomeServiceResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_basic_service_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *HelloRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudEvent    *v1.CloudEvent         `protobuf:"bytes,1,opt,name=cloud_event,json=cloudEvent,proto3" json:"cloud_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_basic_service_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *HelloResponse) GetCloudEvent() *v1.CloudEvent {
	if x != nil {
		return x.CloudEvent
	}
	return nil
}

type HelloResponseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponseEvent) Reset() {
	*x = HelloResponseEvent{}
	mi := &file_basic_service_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponseEvent) ProtoMessage() {}

func (x *HelloResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponseEvent.ProtoReflect.Descriptor instead.
func (*HelloResponseEvent) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *HelloResponseEvent) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

type TalkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkRequest) Reset() {
	*x = TalkRequest{}
	mi := &file_basic_service_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkRequest) ProtoMessage() {}

func (x *TalkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkRequest.ProtoReflect.Descriptor instead.
func (*TalkRequest) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *TalkRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TalkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalkResponse) Reset() {
	*x = TalkResponse{}
	mi := &file_basic_service_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalkResponse) ProtoMessage() {}

func (x *TalkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalkResponse.ProtoReflect.Descriptor instead.
func (*TalkResponse) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *TalkResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type BackgroundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     int64                  `protobuf:"varint,1,opt,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundRequest) Reset() {
	*x = BackgroundRequest{}
	mi := &file_basic_service_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundRequest) ProtoMessage() {}

func (x *BackgroundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundRequest.ProtoReflect.Descriptor instead.
func (*BackgroundRequest) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *BackgroundRequest) GetProcesses() int64 {
	if x != nil {
		return x.Processes
	}
	return 0
}

type BackgroundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CloudEvent    *v1.CloudEvent         `protobuf:"bytes,1,opt,name=cloud_event,json=cloudEvent,proto3" json:"cloud_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundResponse) Reset() {
	*x = BackgroundResponse{}
	mi := &file_basic_service_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundResponse) ProtoMessage() {}

func (x *BackgroundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundResponse.ProtoReflect.Descriptor instead.
func (*BackgroundResponse) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *BackgroundResponse) GetCloudEvent() *v1.CloudEvent {
	if x != nil {
		return x.CloudEvent
	}
	return nil
}

type BackgroundResponseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         State                  `protobuf:"varint,1,opt,name=state,proto3,enum=basic.service.v1.State" json:"state,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Responses     []*SomeServiceResponse `protobuf:"bytes,4,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundResponseEvent) Reset() {
	*x = BackgroundResponseEvent{}
	mi := &file_basic_service_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundResponseEvent) ProtoMessage() {}

func (x *BackgroundResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_basic_service_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundResponseEvent.ProtoReflect.Descriptor instead.
func (*BackgroundResponseEvent) Descriptor() ([]byte, []int) {
	return file_basic_service_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *BackgroundResponseEvent) GetState() State {
	if x != nil {
		return x.State
	}
	return State_PROCESS_STATE_UNSPECIFIED
}

func (x *BackgroundResponseEvent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *BackgroundResponseEvent) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *BackgroundResponseEvent) GetResponses() []*SomeServiceResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_basic_service_v1_service_proto protoreflect.FileDescriptor

const file_basic_service_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ebasic/service/v1/service.proto\x12\x10basic.service.v1\x1a#io/cloudevents/v1/cloudevents.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\x0fSomeServiceData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x8a\x01\n" +
	"\x13SomeServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x125\n" +
	"\x04data\x18\x04 \x01(\v2!.basic.service.v1.SomeServiceDataR\x04data\"[\n" +
	"\x14SomeServiceResponses\x12C\n" +
	"\tresponses\x18\x01 \x03(\v2%.basic.service.v1.SomeServiceResponseR\tresponses\"(\n" +
	"\fHelloRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"O\n" +
	"\rHelloResponse\x12>\n" +
	"\vcloud_event\x18\x01 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\n" +
	"cloudEvent\"0\n" +
	"\x12HelloResponseEvent\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"'\n" +
	"\vTalkRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\fTalkResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\"1\n" +
	"\x11BackgroundRequest\x12\x1c\n" +
	"\tprocesses\x18\x01 \x01(\x03R\tprocesses\"T\n" +
	"\x12BackgroundResponse\x12>\n" +
	"\vcloud_event\x18\x01 \x01(\v2\x1d.io.cloudevents.v1.CloudEventR\n" +
	"cloudEvent\"\x87\x02\n" +
	"\x17BackgroundResponseEvent\x12-\n" +
	"\x05state\x18\x01 \x01(\x0e2\x17.basic.service.v1.StateR\x05state\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12C\n" +
	"\tresponses\x18\x04 \x03(\v2%.basic.service.v1.SomeServiceResponseR\tresponses*\x9d\x01\n" +
	"\x05State\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PROCESS_STATE_PROCESS\x10\x01\x12\x1a\n" +
	"\x16PROCESS_STATE_COMPLETE\x10\x02\x12\x17\n" +
	"\x13PROCESS_STATE_ERROR\x10\x03\x12%\n" +
	"!PROCESS_STATE_COMPLETE_WITH_ERROR\x10\x04BWZUgithub.com/soundphilosopher/basic-grpc-service-go/sdk/basic/service/v1;basicServiceV1b\x06proto3"

var (
	file_basic_service_v1_service_proto_rawDescOnce sync.Once
	file_basic_service_v1_service_proto_rawDescData []byte
)

func file_basic_service_v1_service_proto_rawDescGZIP() []byte {
	file_basic_service_v1_service_proto_rawDescOnce.Do(func() {
		file_basic_service_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_service_v1_service_proto_rawDesc), len(file_basic_service_v1_service_proto_rawDesc)))
	})
	return file_basic_service_v1_service_proto_rawDescData
}

var file_basic_service_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_basic_service_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_basic_service_v1_service_proto_goTypes = []any{
	(State)(0),                      // 0: basic.service.v1.State
	(*SomeServiceData)(nil),         // 1: basic.service.v1.SomeServiceData
	(*SomeServiceResponse)(nil),     // 2: basic.service.v1.SomeServiceResponse
	(*SomeServiceResponses)(nil),    // 3: basic.service.v1.SomeServiceResponses
	(*HelloRequest)(nil),            // 4: basic.service.v1.HelloRequest
	(*HelloResponse)(nil),           // 5: basic.service.v1.HelloResponse
	(*HelloResponseEvent)(nil),      // 6: basic.service.v1.HelloResponseEvent
	(*TalkRequest)(nil),             // 7: basic.service.v1.TalkRequest
	(*TalkResponse)(nil),            // 8: basic.service.v1.TalkResponse
	(*BackgroundRequest)(nil),       // 9: basic.service.v1.BackgroundRequest
	(*BackgroundResponse)(nil),      // 10: basic.service.v1.BackgroundResponse
	(*BackgroundResponseEvent)(nil), // 11: basic.service.v1.BackgroundResponseEvent
	(*v1.CloudEvent)(nil),           // 12: io.cloudevents.v1.CloudEvent
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
}
var file_basic_service_v1_service_proto_depIdxs = []int32{
	1,  // 0: basic.service.v1.SomeServiceResponse.data:type_name -> basic.service.v1.SomeServiceData
	2,  // 1: basic.service.v1.SomeServiceResponses.responses:type_name -> basic.service.v1.SomeServiceResponse
	12, // 2: basic.service.v1.HelloResponse.cloud_event:type_name -> io.cloudevents.v1.CloudEvent
	12, // 3: basic.service.v1.BackgroundResponse.cloud_event:type_name -> io.cloudevents.v1.CloudEvent
	0,  // 4: basic.service.v1.BackgroundResponseEvent.state:type_name -> basic.service.v1.State
	13, // 5: basic.service.v1.BackgroundResponseEvent.started_at:type_name -> google.protobuf.Timestamp
	13, // 6: basic.service.v1.BackgroundResponseEvent.completed_at:type_name -> google.protobuf.Timestamp
	2,  // 7: basic.service.v1.BackgroundResponseEvent.responses:type_name -> basic.service.v1.SomeServiceResponse
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_basic_service_v1_service_proto_init() }
func file_basic_service_v1_service_proto_init() {
	if File_basic_service_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_service_v1_service_proto_rawDesc), len(file_basic_service_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_service_v1_service_proto_goTypes,
		DependencyIndexes: file_basic_service_v1_service_proto_depIdxs,
		EnumInfos:         file_basic_service_v1_service_proto_enumTypes,
		MessageInfos:      file_basic_service_v1_service_proto_msgTypes,
	}.Build()
	File_basic_service_v1_service_proto = out.File
	file_basic_service_v1_service_proto_goTypes = nil
	file_basic_service_v1_service_proto_depIdxs = nil
}
